#!/bin/bash
LOG_FILE="command_output.log"

# Function to print messages in green
print_green() {
    echo -e "\e[0m\e[32m$1\e[0m"
}

# Function to print messages in blue
print_blue() {
    echo -e "\e[36m$1\e[0m"
}

# Function to print messages in red
print_red() {
    echo -e "\e[0m\e[31m$1\e[0m"
}

# Print the blue welcome message
print_blue "-------------------------------------------"
print_blue " Purdue RoboMaster Club: Auto Aiming Suite "
print_blue "       ___________________________         "
print_blue "       \_________________________  \       "
print_blue "        _________________________| |       "
print_blue "        |  ________________________/       "
print_blue "        |  |   __    __    __    __        "
print_blue "        \__/  <__>  <__>  <__>  <__>       "
print_blue "                                           "
print_blue "-------------------------------------------"

# Function to check if MindVision camera is attached and on USB 3.0
check_mindvision_camera() {
    echo "Checking for MindVision camera..."
    local retries=0
    local max_retries=3

    while (( retries < max_retries )); do
        success_count=0
        for i in {1..20}; do
            if lsusb | grep -q "MindVision"; then
                ((success_count++))
            else
                success_count=0
            fi
            sleep 0.2
        done

        if [[ $success_count -eq 20 ]]; then
            # Ensure camera is USB 3.0
            bus=$(lsusb | grep "MindVision" | awk '{print $2}' | sed 's/^0*//')
            speed=$(lsusb -t | grep "Bus 0*$bus" | grep -oP ', \K[0-9]+[MGK]?' | head -n1)
            speed_value=$(echo "$speed" | sed 's/[^0-9]*//g')

            echo "MindVision camera detected on bus $bus with speed $speed."

            if [[ "$speed_value" -lt 5000 ]]; then
                print_red "[!] WARN: MindVision camera is not connected to a USB 3.0 bus! Reloading USB Drivers... (attempt $((retries+1))/$max_retries)"
                ((retries++))
                rebind_usb
                continue
            else
                print_green "[☺] MindVision camera detected on USB 3.0 bus [$bus] with speed ${speed}."
                return 0
            fi
        else
            print_red "[!] WARN: MindVision camera not detected (attempt $((retries+1))/$max_retries)"
            ((retries++))
            rebind_usb
        fi
    done

    print_red "[!] ERROR: MindVision camera not detected or not on USB 3.0 after $max_retries attempts."
    return 1
}

rebind_usb() {
    # Get all USB controller PCI IDs
    usb_ids=$(lspci | grep -i usb | awk '{print "0000:" $1}')

    # Unbind all USB controllers
    for id in $usb_ids; do
        echo "Unbinding $id"
        echo "purdueRM2023" | sudo -S echo -n "$id" | sudo tee "/sys/bus/pci/devices/$id/driver/unbind" > /dev/null
    done

    sleep 0.5

    # Rebind all USB controllers
    for id in $usb_ids; do
        echo "Rebinding $id"
        echo "purdueRM2023" | sudo -S echo -n "$id" | sudo tee "/sys/bus/pci/drivers/xhci_hcd/bind" > /dev/null
    done
}

# Function to clean the workspace
clean() {
    print_green "Cleaning workspace..."
    rm -rf build install log Testing $LOG_FILE
    print_green "Clean complete."
}

# Function to build the project
build() {
    print_green "[*] Building project with Release configuration and optimization flags."

    # Last two args needed to correctly build the livox lidar driver
    build_args="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O3 -DROS_EDITION=ROS2 -DHUMBLE_ROS=humble"

    # Add the DEBUG flag if '--debug' or '-d' was provided
    if [[ "$debug" == "true" ]]; then
        build_args="-DCMAKE_CXX_FLAGS=-DDEBUG $build_args"
    fi

    if [[ "$quiet" == "true" ]]; then
        colcon build --symlink-install --cmake-args $build_args --allow-overriding opencv_armor_detector >> "$LOG_FILE" 2>&1
    else
        colcon build --symlink-install --cmake-args $build_args --allow-overriding opencv_armor_detector
    fi

    if [ $? -eq 0 ]; then
        # print checkmark
        print_green "[☺] Build successful."
        sleep 0.2
        source install/setup.sh
    else
        print_red "Build failed. See $LOG_FILE for more information."
        exit 1
    fi
}

# Function to run tests for each ROS module (non-recursively at first)
test() {
    print_green "Running tests for ROS modules..."

    # Run build first
    build

    # Check if a package name is provided
    local package_name=$1
    if [[ $package_name ]]; then
        source install/setup.sh
        res=$(ros2 pkg list | grep -c "$package_name$")
        if [[ $res -ne 1 ]]; then
            print_red "Package [$package_name] not found for testing"
            exit 1
        fi
    fi

    # Run tests
    if [[ -z "$package_name" ]]; then
        print_green "Running all tests..."
    else
        print_green "Running tests for package: $package_name"
    fi
    if [[ "$quiet" == "true" ]]; then
        if [[ -n "$package_name" ]]; then
            colcon test --packages-select "$package_name" >> "$LOG_FILE" 2>&1
        else
            colcon test >> "$LOG_FILE" 2>&1
        fi
        colcon test-result --verbose >> "$LOG_FILE" 2>&1
    else
        if [[ -n "$package_name" ]]; then
            colcon test --packages-select "$package_name"
        else
            colcon test
        fi
        colcon test-result --verbose
    fi

    # Check if tests passed
    if [ $? -ne 0 ]; then
        print_red "Tests failed. See $LOG_FILE for more information."
        exit 1
    fi

    print_green "Test execution complete."
}

# Function to run a ROS2 launch command
run() {
    if [[ -z "$1" ]]; then
        print_red "Error: No launch argument provided."
        echo "Usage: $0 run <launch_file>"
        exit 1
    fi

    launch_file="$1"
    
    # Run build first
    build

    # Ensure Camera is connected
    check_mindvision_camera

    print_green "[*] Running ROS2 launch: prm_launch $launch_file"
    ros2 launch prm_launch "$launch_file"
    if [ $? -ne 0 ]; then
        print_red "Launch failed."
        exit 1
    fi
}

# Parse script options
while [[ $# -gt 0 ]]; do
    case "$1" in
        -q|--quiet)
            quiet=true
            shift
            ;;
        -d|--debug)
            debug=true
            shift
            ;;
        build)
            build
            shift
            ;;
        clean)
            clean
            shift
            ;;
        test)
            shift
            test "$1" # Pass the next argument (package name) to the test function
            shift
            ;;
        run)
            shift
            run "$@"
            shift $#
            ;;
        *)
            echo "Usage: $0 [--quiet] [--debug] {build|clean|test [package_name]|run <launch_file>}"
            exit 1
            ;;
    esac
done

exit 0