name: Run Colcon Tests

on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  colcon-test:
    runs-on: ubuntu-latest

    steps:
      # Use the Docker image as the environment
      - name: Run Docker Container
        uses: addnab/docker-run-action@v3
        with:
          image: federicolanzani/opencv-cuda  # Use the CUDA-enabled OpenCV image
          options: --gpus all  # Enable GPU support
          run: |
            # Install ROS2 Foxy
            sudo apt update
            sudo apt install -y curl gnupg2 lsb-release
            curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
            sudo apt update
            sudo apt install -y ros-foxy-desktop

            # Source ROS2 setup
            source /opt/ros/foxy/setup.bash

            # Install dependencies
            sudo apt update
            rosdep update
            rosdep install --from-paths src --ignore-src -r -y

            # Make the run script executable
            chmod +x ./run

            # Run build and tests
            ./run test
