name: Run Colcon Tests

on:
  push:
    branches:
      - main
      - ci
  pull_request:

jobs:
  colcon-test:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run build and tests using the run script
      - name: Run build and tests
        run: |
          source /opt/ros/foxy/setup.sh  # Source ROS 2 Foxy
          chmod +x ./run  # Ensure the run script is executable
          nvcc -V  # Check the CUDA version
          ./run test  # Run your test script
